APU Note Mode (alternative version of #334)
aduros/wasm4 pull request #706
Opened 2024-04-17 16:51 UTC by JerwuQu

This is another go at #333, but with a slightly different approach from #334.

Big thanks to @marler8997 for the detailed proposal and the other PR!

Has been tested working on both web and native.

## Reasoning

Since frequencies sent to `tone` are integers, we lose quite a bit of precision when it comes to playing lower notes. This PR implements a variant of #333 to make `tone` capable of playing MIDI notes. We have 16 bits per frequency, which is split up into 8 bits for the note, and 8 bits for optional pitch bend, as to not be limited to pure notes.

It turns out the implementation for this is very simple (JS implementation required less than 15 lines!), and since the flag is new and optional it doesn't affect any prior carts. In my opinion this feature is overdue.

## Usage

Instead of calling `tone` with frequencies, you supply it with notes. The list of MIDI notes is easily googlable and easier to use than frequencies: https://inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies

```c
// Play A4 (440Hz)
tone(69, 0, 0, TONE_NOTE_MODE)
// Play A4 bent halfway up to the next note (A#4)
tone(69 | 128 << 8, 0, 0, TONE_NOTE_MODE)
```

One could compare the pitch bends to cents between semitones in music, where 128 bend would be the equivalent to 50 cents.

## Compared to #334 in short:
- `TONE_NOTE_MODE` flag for `tone` rather than a system flag.
- Puts the main note in the lower bits rather than the upper bits (i.e. `tone(note | bend << 8, ...)` rather than `tone(bend | note << 8, ...)`.)

2024-04-17 17:01 UTC, marler8997 commented
Modifications seem fine to me, Id be happy with or without them.

2024-04-18 03:01 UTC, aduros requested changes
This feels really clean, I like the small adjustments over the other PR 🙂 

Could you also add a short tip somewhere to the doc page here? https://wasm4.org/docs/guides/audio

2024-04-18 16:36 UTC, JerwuQu commented on runtimes/native/src/apu.c
> +static int lerpf (float value1, float value2, float t) {
Thanks! Could've been sure I changed that...

2024-04-18 16:50 UTC, aduros approved these changes

2024-04-18 16:50 UTC, merged